#define MAINPREFIX z
#define PREFIX greenmag
#define PREFIX_BEAUTIFIED GreenMag
#define QPREFIX_BEAUTIFIED QUOTE(PREFIX_BEAUTIFIED)

#include "script_version.hpp"

#define VERSION         MAJOR.MINOR
#define VERSION_STR     MAJOR.MINOR.PATCHLVL.BUILD
#define VERSION_AR      MAJOR,MINOR,PATCHLVL,BUILD
#define VERSION_PLUGIN  MAJOR.MINOR.PATCHLVL.BUILD

#define REQUIRED_VERSION 1.94

#ifdef COMPONENT_BEAUTIFIED
    #define COMPONENT_NAME QUOTE(PREFIX_BEAUTIFIED COMPONENT_BEAUTIFIED)
#else
    #define COMPONENT_NAME QUOTE(PREFIX COMPONENT)
#endif
