PREP(addempty);
//####
PREP(beltactions);
PREP(createBeltLayer);
PREP(createSecondBeltLayer);
//####
PREP(createRefill);
PREP(createFillAction);
PREP(createFillActionBelt);
//####
PREP(createUnload);
PREP(createUnloadAction);
PREP(createUnloadActionBelt);
PREP(createUnloadActionBeltItem);
//####
PREP(createUnpack);
PREP(unpack);
//####
PREP(getFallbackAmmotype);
PREP(getFallbackAmmotypeBelt);
PREP(getFallbackBulletOrBelt);
PREP(addBelt);
PREP(calcTime);
